baseurl = "https://acanthiza.netlify.com/"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
languageCode = "en-us"
title = "Acanthiza"
#theme = "hugo-theme-hello-friend"
copyright = ""
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Enable to show reading time in minutes for posts
  showReadingTime = false

[params.logo]
  logoText = "data rides nature"
#   or
#
#   path = "/img/your-example-logo.svg"
#   alt = "Your example logo alt text"

[social]
    github  = "https://github.com/acanthiza/acanthiza"
    twitter = "https://twitter.com/acanthiza"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
  [[menu.main]]
    identifier = "Code"
    name = "Code"
    url = "https://github.com/Acanthiza/acanthiza"
